kind = "DojoModel"
class_hash = "0xaecb2a72930d9e500fe399b1e9b2fb5e9dd83b7d1d78822cd2c4b2ef089f2e"
original_class_hash = "0xaecb2a72930d9e500fe399b1e9b2fb5e9dd83b7d1d78822cd2c4b2ef089f2e"
abi = "manifests/dev/abis/base/models/blobbar_models_blobtender_current_client.json"
name = "blobbar::models::blobtender::current_client"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "index"
type = "u32"
key = false

[[members]]
name = "order"
type = "u8"
key = false
