kind = "DojoModel"
class_hash = "0x6d671d3df25f33a6994e65a3160b8874633769fc85d19d3a6a668ea375fdf90"
original_class_hash = "0x6d671d3df25f33a6994e65a3160b8874633769fc85d19d3a6a668ea375fdf90"
abi = "manifests/dev/abis/base/models/blobbar_models_blobtender_blobtender.json"
name = "blobbar::models::blobtender::blobtender"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "level"
type = "Level"
key = false

[[members]]
name = "position"
type = "Vec2"
key = false

[[members]]
name = "serving"
type = "u8"
key = false

[[members]]
name = "clients_served"
type = "u32"
key = false

[[members]]
name = "high_score"
type = "u32"
key = false

[[members]]
name = "blobert"
type = "Seed"
key = false

[[members]]
name = "start_time"
type = "u64"
key = false
