kind = "DojoModel"
class_hash = "0x1c51f0d840a4cb56bcf7332e115b8b613ce04acf15d9f55e319914b600b0e4e"
original_class_hash = "0x1c51f0d840a4cb56bcf7332e115b8b613ce04acf15d9f55e319914b600b0e4e"
abi = "manifests/dev/abis/base/models/blobbar_models_blobtender_blobtender.json"
name = "blobbar::models::blobtender::blobtender"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "level"
type = "Level"
key = false

[[members]]
name = "position"
type = "Vec2"
key = false

[[members]]
name = "serving"
type = "DrinkType"
key = false

[[members]]
name = "points"
type = "u32"
key = false

[[members]]
name = "blobert"
type = "Seed"
key = false

[[members]]
name = "start_time"
type = "u64"
key = false
