kind = "DojoContract"
class_hash = "0x652403a16d931ace463f5eedd4bdcc7b79c3a26ec19caa1a37a25c9545c6313"
original_class_hash = "0x652403a16d931ace463f5eedd4bdcc7b79c3a26ec19caa1a37a25c9545c6313"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blobbar_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "blobbar::systems::actions::actions"
