kind = "DojoContract"
class_hash = "0x2abc4f9b14364c9bf0f28d6b2ba015a4f9915625e24e7dfeb10ac6f5fed3e66"
original_class_hash = "0x2abc4f9b14364c9bf0f28d6b2ba015a4f9915625e24e7dfeb10ac6f5fed3e66"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blobbar_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "blobbar::systems::actions::actions"
