kind = "DojoContract"
class_hash = "0x446cd408777d2c8ca4f5eddb83d8bfaef7f818d53d0d340edd83180c13842f5"
original_class_hash = "0x446cd408777d2c8ca4f5eddb83d8bfaef7f818d53d0d340edd83180c13842f5"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blobbar_blobert_seeder_Seeder.json"
reads = []
writes = []
computed = []
name = "blobbar::blobert::seeder::Seeder"
