kind = "DojoContract"
class_hash = "0x2688ed42e54f240fcec58225dd11dd372bcfa5e83cb2ff0e6fa49fa0cf2ceb8"
original_class_hash = "0x2688ed42e54f240fcec58225dd11dd372bcfa5e83cb2ff0e6fa49fa0cf2ceb8"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blobbar_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "blobbar::systems::actions::actions"
