kind = "DojoContract"
class_hash = "0x7c247b2c1749b82cb87249012f524b494b052edea07470c862d9da49849b95e"
original_class_hash = "0x7c247b2c1749b82cb87249012f524b494b052edea07470c862d9da49849b95e"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blobbar_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "blobbar::systems::actions::actions"
