kind = "DojoContract"
class_hash = "0x6d2d86e597fc7ce99c562cf7d6904f75e57ea60acf83118c67ee4e07c355f27"
original_class_hash = "0x6d2d86e597fc7ce99c562cf7d6904f75e57ea60acf83118c67ee4e07c355f27"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blobbar_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "blobbar::systems::actions::actions"
