kind = "DojoContract"
class_hash = "0x1c671d32a5938b013b0d99e2288b5ddb55a67369d7b37a7dd4d8a8b7552681e"
original_class_hash = "0x1c671d32a5938b013b0d99e2288b5ddb55a67369d7b37a7dd4d8a8b7552681e"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blobbar_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "blobbar::systems::actions::actions"
