kind = "DojoContract"
class_hash = "0x5aabcee77eefa2f0088afc9dac23f651360b434dbcbcb05e9738b0052456363"
original_class_hash = "0x5aabcee77eefa2f0088afc9dac23f651360b434dbcbcb05e9738b0052456363"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blobbar_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "blobbar::systems::actions::actions"
