kind = "DojoContract"
class_hash = "0x29cd80a097c7ae5ceace6867d6c0b5e31a6016944e067b8986b78f897108bf"
original_class_hash = "0x29cd80a097c7ae5ceace6867d6c0b5e31a6016944e067b8986b78f897108bf"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blobbar_blobert_seeder_Seeder.json"
reads = []
writes = []
computed = []
name = "blobbar::blobert::seeder::Seeder"
