kind = "DojoContract"
class_hash = "0x74d61aed8e52086109bef12b3e24fe3f2a0217d15eecf6d070845685818349a"
original_class_hash = "0x74d61aed8e52086109bef12b3e24fe3f2a0217d15eecf6d070845685818349a"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blobbar_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "blobbar::systems::actions::actions"
