kind = "DojoModel"
class_hash = "0x730748baa8dd4e4bb2dac90e9d37a691e09931105fbdc5f194ea402acbbc672"
original_class_hash = "0x730748baa8dd4e4bb2dac90e9d37a691e09931105fbdc5f194ea402acbbc672"
abi = "manifests/dev/abis/base/models/blobbar_models_position_position.json"
name = "blobbar::models::position::position"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "vec"
type = "Vec2"
key = false
